import type { Client, Article, Fournisseur, Commande, BonLivraison, PurchaseOrder, Reception, Trip, Livreur } from "./store"

const today = new Date()
const daysAgo = (n: number) => new Date(today.getTime() - n * 86400000).toISOString().slice(0, 10)

// ── Clients ──────────────────────────────────────────────────────────────────
export const SEED_CLIENTS: Client[] = [
  {
    id: "seed-cl-001",
    nom: "Épicerie Al Amal",
    secteur: "Hay Hassani",
    zone: "Casablanca Sud",
    type: "epicerie",
    taille: "50-100kg",
    typeProduits: "moyenne",
    rotation: "journalier",
    modalitePaiement: "cash",
    plafondCredit: 5000,
    creditAutorise: false,
    creditSolde: 0,
    telephone: "0661234567",
    email: "alaimal@demo.ma",
    adresse: "12 Rue Al Amal, Hay Hassani",
    gpsLat: 33.536, gpsLng: -7.655,
    createdBy: "seed",
    createdAt: daysAgo(30),
    segment: "standard",
    loyaltyPoints: 120,
    loyaltyOptIn: true,
  },
  {
    id: "seed-cl-002",
    nom: "Superette Nour",
    secteur: "Ain Chock",
    zone: "Casablanca Est",
    type: "superette",
    taille: "150-300kg",
    typeProduits: "haute_gamme",
    rotation: "4j/6",
    modalitePaiement: "credit_7",
    plafondCredit: 20000,
    creditAutorise: true,
    creditSolde: 3200,
    telephone: "0662345678",
    email: "nour.superette@demo.ma",
    adresse: "45 Bd Hassan II, Ain Chock",
    gpsLat: 33.553, gpsLng: -7.543,
    createdBy: "seed",
    createdAt: daysAgo(45),
    segment: "vip",
    loyaltyPoints: 850,
    loyaltyOptIn: true,
  },
  {
    id: "seed-cl-003",
    nom: "Marché Centrale Wholesale",
    secteur: "Derb Omar",
    zone: "Casablanca Centre",
    type: "grossiste",
    taille: "500kg+",
    typeProduits: "entree_gamme",
    rotation: "journalier",
    modalitePaiement: "virement",
    plafondCredit: 80000,
    creditAutorise: true,
    creditSolde: 15400,
    telephone: "0521123456",
    email: "centrale.wholesale@demo.ma",
    adresse: "Derb Omar, Marché de Gros",
    gpsLat: 33.591, gpsLng: -7.617,
    createdBy: "seed",
    createdAt: daysAgo(60),
    segment: "grossiste",
    loyaltyPoints: 2400,
    loyaltyOptIn: false,
  },
  {
    id: "seed-cl-004",
    nom: "Restaurant Le Patio",
    secteur: "Anfa",
    zone: "Casablanca Ouest",
    type: "restaurant",
    taille: "150-300kg",
    typeProduits: "haute_gamme",
    rotation: "3/6",
    modalitePaiement: "cheque",
    plafondCredit: 30000,
    creditAutorise: true,
    creditSolde: 7800,
    telephone: "0522987654",
    email: "contact@lepatio-demo.ma",
    adresse: "78 Bd d'Anfa, Casablanca",
    gpsLat: 33.587, gpsLng: -7.668,
    createdBy: "seed",
    createdAt: daysAgo(20),
    segment: "vip",
    loyaltyPoints: 320,
    loyaltyOptIn: true,
  },
  {
    id: "seed-cl-005",
    nom: "Épicerie Badr",
    secteur: "Sidi Moumen",
    zone: "Casablanca Est",
    type: "epicerie",
    taille: "50-100kg",
    typeProduits: "entree_gamme",
    rotation: "2/6",
    modalitePaiement: "cash",
    plafondCredit: 3000,
    creditAutorise: false,
    creditSolde: 0,
    telephone: "0663456789",
    adresse: "Cité Attacharouk, Sidi Moumen",
    gpsLat: 33.590, gpsLng: -7.490,
    createdBy: "seed",
    createdAt: daysAgo(15),
    segment: "standard",
    loyaltyPoints: 45,
    loyaltyOptIn: false,
  },
  {
    id: "seed-cl-006",
    nom: "Hôtel Mogador Essaouira",
    secteur: "Essaouira",
    zone: "Région Marrakech-Safi",
    type: "hotel",
    taille: "350-500kg",
    typeProduits: "haute_gamme",
    rotation: "4j/6",
    modalitePaiement: "virement",
    plafondCredit: 60000,
    creditAutorise: true,
    creditSolde: 22000,
    telephone: "0524476543",
    email: "approvisionnement@mogador-demo.ma",
    adresse: "Rue Laâlouj, Essaouira",
    gpsLat: 31.508, gpsLng: -9.760,
    createdBy: "seed",
    createdAt: daysAgo(90),
    segment: "vip",
    loyaltyPoints: 1850,
    loyaltyOptIn: true,
  },
]

// ── Articles ─────────────────────────────────────────────────────────────────
export const SEED_ARTICLES: Article[] = [
  {
    id: "seed-art-001",
    nom: "Tomates Rondes",
    nomAr: "طماطم",
    famille: "Légumes",
    unite: "kg",
    um: "Caisse",
    colisageParUM: 15,
    colisageCaisses: 15,
    stockDisponible: 450,
    stockDefect: 12,
    stockTheorique: 450,
    shelfLifeJours: 7,
    alerteShelfLifeJours: 2,
    prixAchat: 3.2,
    pvMethode: "pourcentage",
    pvValeur: 35,
    lots: [{ lotId: "LOT-" + daysAgo(2), dateReception: daysAgo(2), quantite: 300, fournisseurNom: "Ferme Souss Agri" }],
    historiquePrixAchat: [
      { date: daysAgo(7), fournisseurId: "seed-fo-001", fournisseurNom: "Ferme Souss Agri", prixAchat: 3.0, quantite: 200 },
      { date: daysAgo(2), fournisseurId: "seed-fo-001", fournisseurNom: "Ferme Souss Agri", prixAchat: 3.2, quantite: 300 },
    ],
  },
  {
    id: "seed-art-002",
    nom: "Pommes de Terre",
    nomAr: "بطاطس",
    famille: "Légumes",
    unite: "kg",
    um: "Caisse",
    colisageParUM: 25,
    colisageCaisses: 25,
    stockDisponible: 1200,
    stockDefect: 30,
    shelfLifeJours: 30,
    alerteShelfLifeJours: 5,
    prixAchat: 2.1,
    pvMethode: "pourcentage",
    pvValeur: 30,
    historiquePrixAchat: [
      { date: daysAgo(14), fournisseurId: "seed-fo-002", fournisseurNom: "Coopérative Meknès", prixAchat: 2.0, quantite: 800 },
      { date: daysAgo(3), fournisseurId: "seed-fo-002", fournisseurNom: "Coopérative Meknès", prixAchat: 2.1, quantite: 600 },
    ],
  },
  {
    id: "seed-art-003",
    nom: "Fraises Kenitra",
    nomAr: "فراولة",
    famille: "Fruits",
    unite: "kg",
    um: "Barquette",
    colisageParUM: 0.5,
    stockDisponible: 85,
    stockDefect: 8,
    shelfLifeJours: 4,
    alerteShelfLifeJours: 1,
    prixAchat: 18.0,
    pvMethode: "pourcentage",
    pvValeur: 40,
    lots: [{ lotId: "LOT-" + daysAgo(1), dateReception: daysAgo(1), quantite: 85, fournisseurNom: "Coopérative Gharb" }],
  },
  {
    id: "seed-art-004",
    nom: "Oranges Navel",
    nomAr: "برتقال",
    famille: "Agrumes",
    unite: "kg",
    um: "Filet 5kg",
    colisageParUM: 5,
    colisageCaisses: 20,
    stockDisponible: 680,
    stockDefect: 15,
    shelfLifeJours: 21,
    alerteShelfLifeJours: 4,
    prixAchat: 4.5,
    pvMethode: "pourcentage",
    pvValeur: 25,
    historiquePrixAchat: [
      { date: daysAgo(10), fournisseurId: "seed-fo-001", fournisseurNom: "Ferme Souss Agri", prixAchat: 4.2, quantite: 400 },
    ],
  },
  {
    id: "seed-art-005",
    nom: "Avocats Hass",
    nomAr: "أفوكادو",
    famille: "Fruits",
    unite: "kg",
    um: "Caisse",
    colisageParUM: 10,
    colisageCaisses: 10,
    stockDisponible: 120,
    stockDefect: 5,
    shelfLifeJours: 10,
    alerteShelfLifeJours: 3,
    prixAchat: 22.0,
    pvMethode: "pourcentage",
    pvValeur: 38,
    historiquePrixAchat: [],
  },
  {
    id: "seed-art-006",
    nom: "Carottes",
    nomAr: "جزر",
    famille: "Légumes",
    unite: "kg",
    um: "Sac",
    colisageParUM: 20,
    colisageCaisses: 20,
    stockDisponible: 380,
    stockDefect: 10,
    shelfLifeJours: 21,
    alerteShelfLifeJours: 3,
    prixAchat: 1.8,
    pvMethode: "pourcentage",
    pvValeur: 30,
  },
  {
    id: "seed-art-007",
    nom: "Citrons Eureka",
    nomAr: "ليمون",
    famille: "Agrumes",
    unite: "kg",
    um: "Caisse",
    colisageParUM: 15,
    colisageCaisses: 15,
    stockDisponible: 210,
    stockDefect: 4,
    shelfLifeJours: 28,
    alerteShelfLifeJours: 5,
    prixAchat: 5.0,
    pvMethode: "pourcentage",
    pvValeur: 28,
  },
  {
    id: "seed-art-008",
    nom: "Bananes Cavendish",
    nomAr: "موز",
    famille: "Fruits Tropicaux",
    unite: "kg",
    um: "Régime",
    colisageParUM: 18,
    stockDisponible: 270,
    stockDefect: 20,
    shelfLifeJours: 7,
    alerteShelfLifeJours: 2,
    prixAchat: 7.5,
    pvMethode: "pourcentage",
    pvValeur: 32,
  },
]

// ── Fournisseurs ──────────────────────────────────────────────────────────────
export const SEED_FOURNISSEURS: Fournisseur[] = [
  {
    id: "seed-fo-001",
    nom: "Ferme Souss Agri",
    contact: "Mohammed Ait Benhaddou",
    telephone: "0661987654",
    email: "souss.agri@demo.ma",
    adresse: "Douar Oulad Said, Agadir",
    ville: "Agadir",
    region: "Souss-Massa",
    specialites: ["Tomates Rondes", "Avocats Hass", "Oranges Navel"],
    modalitePaiement: "virement",
    delaiPaiement: 30,
    ice: "001234567000045",
    itineraires: [
      { lat: 30.4278, lng: -9.5981, nom: "Marché de Gros Agadir" },
      { lat: 33.5912, lng: -7.6116, nom: "Marché de Gros Casablanca" },
    ],
  },
  {
    id: "seed-fo-002",
    nom: "Coopérative Meknès",
    contact: "Rachida Benali",
    telephone: "0535445566",
    email: "coop.meknes@demo.ma",
    adresse: "Route d'Azrou, Meknès",
    ville: "Meknès",
    region: "Fès-Meknès",
    specialites: ["Pommes de Terre", "Carottes", "Oignons"],
    modalitePaiement: "cheque",
    delaiPaiement: 15,
    itineraires: [
      { lat: 33.8935, lng: -5.5473, nom: "Marché Meknès" },
    ],
  },
  {
    id: "seed-fo-003",
    nom: "Coopérative Gharb",
    contact: "Khalid Zemmouri",
    telephone: "0537789012",
    email: "gharb.coop@demo.ma",
    adresse: "Sidi Slimane, Gharb",
    ville: "Sidi Slimane",
    region: "Rabat-Salé-Kénitra",
    specialites: ["Fraises Kenitra", "Clémentines", "Poivrons"],
    modalitePaiement: "cash",
    delaiPaiement: 7,
    itineraires: [
      { lat: 34.2667, lng: -5.9317, nom: "Marché Sidi Slimane" },
    ],
  },
]

// ── Livreurs ─────────────────────────────────────────────────────────────────
export const SEED_LIVREURS: Livreur[] = [
  {
    id: "seed-lv-001",
    type: "interne",
    nom: "Benhaddou",
    prenom: "Youssef",
    telephone: "0661112233",
    cin: "AB123456",
    typeVehicule: "camion",
    marqueVehicule: "Mercedes Atego",
    matricule: "A-12345-B",
    capaciteCaisses: 200,
    capaciteTonnage: 5000,
    actif: true,
  },
  {
    id: "seed-lv-002",
    type: "interne",
    nom: "Oukili",
    prenom: "Hamza",
    telephone: "0662223344",
    cin: "CD789012",
    typeVehicule: "camionnette",
    marqueVehicule: "Renault Master",
    matricule: "B-67890-C",
    capaciteCaisses: 80,
    capaciteTonnage: 1500,
    actif: true,
  },
]

// ── Commandes ─────────────────────────────────────────────────────────────────
export const SEED_COMMANDES: Commande[] = [
  {
    id: "seed-cmd-001",
    date: daysAgo(5),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-001",
    clientNom: "Épicerie Al Amal",
    secteur: "Hay Hassani",
    zone: "Casablanca Sud",
    gpsLat: 33.536, gpsLng: -7.655,
    heurelivraison: "08:00",
    statut: "livre",
    emailDestinataire: "alaimal@demo.ma",
    lignes: [
      { articleId: "seed-art-001", articleNom: "Tomates Rondes", unite: "kg", quantite: 30, prixUnitaire: 4.32, prixVente: 4.32, total: 129.6 },
      { articleId: "seed-art-006", articleNom: "Carottes", unite: "kg", quantite: 20, prixUnitaire: 2.34, prixVente: 2.34, total: 46.8 },
    ],
  },
  {
    id: "seed-cmd-002",
    date: daysAgo(3),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-002",
    clientNom: "Superette Nour",
    secteur: "Ain Chock",
    zone: "Casablanca Est",
    gpsLat: 33.553, gpsLng: -7.543,
    heurelivraison: "09:30",
    statut: "valide",
    emailDestinataire: "nour.superette@demo.ma",
    lignes: [
      { articleId: "seed-art-003", articleNom: "Fraises Kenitra", unite: "kg", quantite: 10, prixUnitaire: 25.2, prixVente: 25.2, total: 252 },
      { articleId: "seed-art-005", articleNom: "Avocats Hass", unite: "kg", quantite: 15, prixUnitaire: 30.36, prixVente: 30.36, total: 455.4 },
    ],
  },
  {
    id: "seed-cmd-003",
    date: daysAgo(1),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-003",
    clientNom: "Marché Centrale Wholesale",
    secteur: "Derb Omar",
    zone: "Casablanca Centre",
    gpsLat: 33.591, gpsLng: -7.617,
    heurelivraison: "06:00",
    statut: "en_attente",
    emailDestinataire: "centrale.wholesale@demo.ma",
    lignes: [
      { articleId: "seed-art-002", articleNom: "Pommes de Terre", unite: "kg", quantite: 500, prixUnitaire: 2.73, prixVente: 2.73, total: 1365 },
      { articleId: "seed-art-004", articleNom: "Oranges Navel", unite: "kg", quantite: 200, prixUnitaire: 5.625, prixVente: 5.625, total: 1125 },
      { articleId: "seed-art-007", articleNom: "Citrons Eureka", unite: "kg", quantite: 100, prixUnitaire: 6.4, prixVente: 6.4, total: 640 },
    ],
  },
  {
    id: "seed-cmd-004",
    date: daysAgo(2),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-004",
    clientNom: "Restaurant Le Patio",
    secteur: "Anfa",
    zone: "Casablanca Ouest",
    gpsLat: 33.587, gpsLng: -7.668,
    heurelivraison: "07:00",
    statut: "en_transit",
    emailDestinataire: "contact@lepatio-demo.ma",
    lignes: [
      { articleId: "seed-art-001", articleNom: "Tomates Rondes", unite: "kg", quantite: 25, prixUnitaire: 4.32, prixVente: 4.32, total: 108 },
      { articleId: "seed-art-003", articleNom: "Fraises Kenitra", unite: "kg", quantite: 5, prixUnitaire: 25.2, prixVente: 25.2, total: 126 },
      { articleId: "seed-art-008", articleNom: "Bananes Cavendish", unite: "kg", quantite: 30, prixUnitaire: 9.9, prixVente: 9.9, total: 297 },
    ],
  },
  {
    id: "seed-cmd-005",
    date: daysAgo(7),
    commercialId: "seed",
    commercialNom: "Admin Demo",
    clientId: "seed-cl-006",
    clientNom: "Hôtel Mogador Essaouira",
    secteur: "Essaouira",
    zone: "Région Marrakech-Safi",
    gpsLat: 31.508, gpsLng: -9.760,
    heurelivraison: "10:00",
    statut: "livre",
    emailDestinataire: "approvisionnement@mogador-demo.ma",
    lignes: [
      { articleId: "seed-art-004", articleNom: "Oranges Navel", unite: "kg", quantite: 80, prixUnitaire: 5.625, prixVente: 5.625, total: 450 },
      { articleId: "seed-art-005", articleNom: "Avocats Hass", unite: "kg", quantite: 40, prixUnitaire: 30.36, prixVente: 30.36, total: 1214.4 },
      { articleId: "seed-art-008", articleNom: "Bananes Cavendish", unite: "kg", quantite: 60, prixUnitaire: 9.9, prixVente: 9.9, total: 594 },
    ],
  },
]

// ── Bons de Livraison ─────────────────────────────────────────────────────────
export const SEED_BONS_LIVRAISON: BonLivraison[] = [
  {
    id: "seed-bl-001",
    date: daysAgo(5),
    tripId: "seed-tr-001",
    commandeId: "seed-cmd-001",
    clientNom: "Épicerie Al Amal",
    secteur: "Hay Hassani",
    zone: "Casablanca Sud",
    livreurNom: "Youssef Benhaddou",
    prevendeurNom: "Admin Demo",
    lignes: [
      { articleNom: "Tomates Rondes", unite: "kg", quantite: 30, prixUnitaire: 4.32, total: 129.6 },
      { articleNom: "Carottes", unite: "kg", quantite: 20, prixUnitaire: 2.34, total: 46.8 },
    ],
    montantTotal: 176.4,
    tva: 0,
    montantTTC: 176.4,
    statut: "encaissé",
    statutLivraison: "livre",
    heureLivraisonReelle: "08:15",
    nbCaisseGros: 2,
    nbCaisseDemi: 2,
  },
  {
    id: "seed-bl-002",
    date: daysAgo(7),
    tripId: "seed-tr-002",
    commandeId: "seed-cmd-005",
    clientNom: "Hôtel Mogador Essaouira",
    secteur: "Essaouira",
    zone: "Région Marrakech-Safi",
    livreurNom: "Hamza Oukili",
    prevendeurNom: "Admin Demo",
    lignes: [
      { articleNom: "Oranges Navel", unite: "kg", quantite: 80, prixUnitaire: 5.625, total: 450 },
      { articleNom: "Avocats Hass", unite: "kg", quantite: 40, prixUnitaire: 30.36, total: 1214.4 },
      { articleNom: "Bananes Cavendish", unite: "kg", quantite: 60, prixUnitaire: 9.9, total: 594 },
    ],
    montantTotal: 2258.4,
    tva: 451.68,
    montantTTC: 2710.08,
    statut: "encaissé",
    statutLivraison: "livre",
    heureLivraisonReelle: "11:30",
    nbCaisseGros: 10,
    nbCaisseDemi: 4,
  },
]

// ── Purchase Orders ───────────────────────────────────────────────────────────
export const SEED_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "seed-po-001",
    date: daysAgo(4),
    articleId: "seed-art-001",
    articleNom: "Tomates Rondes",
    articleUnite: "kg",
    fournisseurId: "seed-fo-001",
    fournisseurNom: "Ferme Souss Agri",
    fournisseurEmail: "souss.agri@demo.ma",
    quantite: 400,
    prixUnitaire: 3.2,
    total: 1280,
    statut: "receptionné",
    notes: "Commande hebdomadaire — priorité qualité A",
    createdBy: "seed",
    montantPaye: 1280,
    statutPaiement: "solde",
    datePaiement: daysAgo(2),
    genereAuto: false,
  },
  {
    id: "seed-po-002",
    date: daysAgo(2),
    articleId: "seed-art-002",
    articleNom: "Pommes de Terre",
    articleUnite: "kg",
    fournisseurId: "seed-fo-002",
    fournisseurNom: "Coopérative Meknès",
    fournisseurEmail: "coop.meknes@demo.ma",
    quantite: 600,
    prixUnitaire: 2.1,
    total: 1260,
    statut: "envoyé",
    notes: "",
    createdBy: "seed",
    montantPaye: 0,
    statutPaiement: "impaye",
    genereAuto: true,
  },
  {
    id: "seed-po-003",
    date: daysAgo(1),
    articleId: "seed-art-003",
    articleNom: "Fraises Kenitra",
    articleUnite: "kg",
    fournisseurId: "seed-fo-003",
    fournisseurNom: "Coopérative Gharb",
    fournisseurEmail: "gharb.coop@demo.ma",
    quantite: 100,
    prixUnitaire: 18.0,
    total: 1800,
    statut: "ouvert",
    notes: "Fraises calibre 30+ uniquement",
    createdBy: "seed",
    montantPaye: 0,
    statutPaiement: "impaye",
    genereAuto: false,
  },
]

// ── Réceptions ────────────────────────────────────────────────────────────────
export const SEED_RECEPTIONS: Reception[] = [
  {
    id: "seed-re-001",
    date: daysAgo(4),
    bonAchatId: "",
    purchaseOrderId: "seed-po-001",
    fournisseurNom: "Ferme Souss Agri",
    source: "purchase_order",
    lignes: [
      {
        articleId: "seed-art-001",
        articleNom: "Tomates Rondes",
        quantiteCommandee: 400,
        quantiteRecue: 395,
        quantiteFacturee: 400,
        prixAchat: 3.2,
        prixFacture: 3.2,
        ecartQte: -5,
        ecartPrix: 0,
        motifReliquat: "5 kg abîmés refusés à la réception",
      },
    ],
    statut: "validée",
    operateurId: "seed",
    notes: "Réception conforme — manque 5 kg qualité insuffisante",
  },
]

// ── Trips ─────────────────────────────────────────────────────────────────────
export const SEED_TRIPS: Trip[] = [
  {
    id: "seed-tr-001",
    numero: "T001",
    date: daysAgo(5),
    livreurId: "seed-lv-001",
    livreurNom: "Youssef Benhaddou",
    vehicule: "Mercedes Atego — A-12345-B",
    commandeIds: ["seed-cmd-001"],
    statut: "terminé",
    itineraire: [
      { lat: 33.536, lng: -7.655, clientNom: "Épicerie Al Amal", ordre: 1 },
    ],
    kmDepart: 12450,
    kmArrivee: 12498,
    kmTotal: 48,
    kmDepartConfirme: true,
    caissesValidees: true,
  },
  {
    id: "seed-tr-002",
    numero: "T002",
    date: daysAgo(7),
    livreurId: "seed-lv-002",
    livreurNom: "Hamza Oukili",
    vehicule: "Renault Master — B-67890-C",
    commandeIds: ["seed-cmd-005"],
    statut: "terminé",
    itineraire: [
      { lat: 31.508, lng: -9.760, clientNom: "Hôtel Mogador Essaouira", ordre: 1 },
    ],
    kmDepart: 34200,
    kmArrivee: 34562,
    kmTotal: 362,
    kmDepartConfirme: true,
    caissesValidees: true,
  },
  {
    id: "seed-tr-003",
    numero: "T003",
    date: daysAgo(2),
    livreurId: "seed-lv-001",
    livreurNom: "Youssef Benhaddou",
    vehicule: "Mercedes Atego — A-12345-B",
    commandeIds: ["seed-cmd-004"],
    statut: "en_cours",
    itineraire: [
      { lat: 33.587, lng: -7.668, clientNom: "Restaurant Le Patio", ordre: 1 },
    ],
    kmDepart: 12498,
    kmDepartConfirme: true,
    caissesValidees: false,
  },
]

// ── Seed function ─────────────────────────────────────────────────────────────
export function seedDemoData(storeRef: typeof import("./store").store) {
  function mergeById<T extends { id: string }>(existing: T[], seeds: T[]): T[] {
    const map = new Map(existing.map(x => [x.id, x]))
    seeds.forEach(s => { if (!map.has(s.id)) map.set(s.id, s) })
    return Array.from(map.values())
  }

  storeRef.saveClients(mergeById(storeRef.getClients(), SEED_CLIENTS))
  storeRef.saveArticles(mergeById(storeRef.getArticles(), SEED_ARTICLES))
  storeRef.saveFournisseurs(mergeById(storeRef.getFournisseurs(), SEED_FOURNISSEURS))
  storeRef.saveCommandes(mergeById(storeRef.getCommandes(), SEED_COMMANDES))
  storeRef.saveBonsLivraison(mergeById(storeRef.getBonsLivraison(), SEED_BONS_LIVRAISON))
  storeRef.savePurchaseOrders(mergeById(storeRef.getPurchaseOrders(), SEED_PURCHASE_ORDERS))
  storeRef.saveReceptions(mergeById(storeRef.getReceptions(), SEED_RECEPTIONS))
  storeRef.saveTrips(mergeById(storeRef.getTrips(), SEED_TRIPS))

  const existing: Livreur[] = (() => {
    try { return JSON.parse(localStorage.getItem("fl_livreurs") ?? "[]") } catch { return [] }
  })()
  localStorage.setItem("fl_livreurs", JSON.stringify(mergeById(existing, SEED_LIVREURS)))
}
